### ISSUE TITLE
User Import Instructions Don't Match Up with the UI

### ISSUE THREAD

**Issue by innomadic** [GibbonEdu/docs#19]
I am using [these docs](https://docs.gibbonedu.org/administrators/getting-started/getting-started-with-gibbon/#users) to set up a new Gibbon installation.   

The instructions say

> Use the following options in the right-hand menu under Admin > User Admin to set up users and access.

## Expected Behavior

I expected the User Manage page (?q=/modules/User%20Admin/user_manage.php)  to have options for Importing Users.  

## Actual Behavior

There is an import section, but it only has says "Import User Photos".   There seem to be some import options under Admin > System Admin > Import From File.

## Steps to Reproduce
Open the Admin > User Admin page

I didn't want to just edit the docs because I'm not sure if I may have something misconfigured.

**Comment by SKuipers** [comment]
Hi @innomadic. Thanks for the heads-up! Yes, the import system was improved in a recent update and the User Import functionality was consolidated into System Admin. It looks like we had [updated the docs here](https://docs.gibbonedu.org/administrators/getting-started/importing-users/) but had missed the paragraph in the page you've lined to. I've updated the docs, thanks! 👍
