### ISSUE TITLE
Screenshots for Custom Fields not shown on the website, but seen in github markdown.

### ISSUE THREAD

**Issue by xjlwi** [GibbonEdu/docs#56]
Hi @SKuipers ,

I noticed that the screenshots are not visible on the webpage. Could you advise please?

## Expected Behavior
https://github.com/GibbonEdu/docs/blob/main/content/administrators/getting-started/customizing-gibbon/custom-fields.md _This is visible_

## Actual Behavior

https://docs.gibbonedu.org/administrators/getting-started/customizing-gibbon/custom-fields/ 
This page isn't visible.

**Comment by SKuipers** [comment]
Thanks for the heads up! I've fixed the images. It looks like the /static directory was not needed as part of the image URL. You should see that they're working now: [Custom Fields](https://docs.gibbonedu.org/administrators/getting-started/customizing-gibbon/custom-fields/) and [Installing on Windows](https://docs.gibbonedu.org/administrators/getting-started/installing-gibbon/install-windows/)
